### ISSUE TITLE
[BUG]: installation could fail without notice 

### ISSUE THREAD

**Issue by Dev-CasperTheGhost** [WhitigolProd/SnailyCAD-Manager#4]
**Describe the bug**

If the folder `snaily-cadv4` already exists in the folder of installation, the CAD will log `Folder already exists` but isn't very clear that this is a fatal error. 

**To Reproduce**

1. Create a folder called `snaily-cadv4`
2. Install the manager app
3. Set the installation path 
4. Install the CAD
5. See error in log "Fatal: folder already exists"

**Expected behavior**

Should probably warn the user the CAD is already installed when selecting the installation path

**Additional context**
Thanks again for creating this great app!

**Comment by WhitigolProd** [comment]
Thanks for the bug report! I will be sure to fix this in the next update.

**Comment by WhitigolProd** [comment]
This has now been resolved. Please update your Manager to `1.0.2` for changes to take effect.

- [Main Release](https://github.com/WhitigolProd/SnailyCAD-Manager/releases/tag/1.0.2)
- [Updater Release](https://github.com/WhitigolProd/scm-updater/releases/tag/1.0.2)
