### ISSUE TITLE
[BUG] Window close button (x) does not close SnailyCAD Manager

### ISSUE THREAD

**Issue by ArgonGlow** [WhitigolProd/SnailyCAD-Manager#7]
**Describe the bug**
Clicking the X/close button at the top-right of the window doesn't close the application.

**To Reproduce**

1. Start SnailyCAD Manager
2. Click on the close/exit button at the top-right of the window
3. Window does not close

**Expected behavior**
The window closes, bar any situations where it might be intended to not do so (i.e. server still running)

**Desktop:**

-   OS: Windows 10
-   Manager Version: 1.0.4

**Additional context**
Closing the app via the taskbar works as expected.

**Comment by WhitigolProd** [comment]
Thank you for bringing this to my attention. You can use `Alt` + `F4` to close the window. As I begin the development on v2, these issues will be fixed.
